pipeline {

    environment {
        imagename = 'cobbgcloud/timeoff'
        dockerimage = ''
    }

    agent any
    stages{
        stage('Checkout SCM') {
            steps{
                git([url: 'https://github.com/cobbgcall/timeoff-management-application.git', branch: 'master'])
            }
        }
        stage('Build Image') {
            script {
                dockerimage = docker.build imagename
            }
        }
        stage('Deploy Image') {
            script {
                docker.withRegistry( 'https://index.docker.io/v1/', registryCredential ) {
                    dockerimage.push("$BUILD_NUMBER")
                    dockerimage.push('latest')
                }
            }
        }
        stage('Remove Unused Image'){
            steps{
                sh "docker rmi $imagename:$BUILD_NUMBER"
                sh "docker rmi $imagename:latest"
            }
        }
    }
}
post {
    cleanup {
        cleanWs()
    }
}